[profile.default]
solc = "0.8.23"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
optimizer = true
optimizer_runs = 1000000
fs_permissions = [
  { access = "write", path = "./deployments" },
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"
fraxtal = "${FRAX_RPC_URL}"
manta = "${MANTA_RPC_URL}"
taiko = "${TAIKO_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
mantle = "${MANTLE_RPC_URL}"
blast = "${BLAST_RPC_URL}"
linea = "${LINEA_RPC_URL}"
bera = "${BERA_RPC_URL}"
bsc = "${BSC_RPC_URL}"
hemi = "${HEMI_RPC_URL}"
ink = "${INK_RPC_URL}"
fraxtal_testnet = "${FRAX_TESTNET_RPC_URL}"
morph_testnet = "${MORPH_TESTNET_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
hemi_testnet = "${HEMI_TESTNET_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
sanko = "${SANKO_RPC_URL}"
nibiru = "${NIBIRU_RPC_URL}"
unichain = "${RPC_URL_UNICHAIN}"

[etherscan]
